# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module Mocha::Mock; end
module ServiceTrade::ApiOperations::Create; end
module ServiceTrade::ApiOperations::Delete; end
module ServiceTrade::ApiOperations::Update; end
